//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
[System.Xml.Serialization.XmlRootAttribute("thing-descriptions", Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0", IsNullable = false)]
public partial class thingdescriptions
{

    private object[] itemsField;

    private string bindingIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bridge-type", typeof(bridgeType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("channel-group-type", typeof(channelGroupType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("channel-type", typeof(channelType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("thing-type", typeof(thingType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bindingId
    {
        get
        {
            return this.bindingIdField;
        }
        set
        {
            this.bindingIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class bridgeType : thingType
{
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(bridgeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class thingType
{

    private bridgeTypeRef[] supportedbridgetyperefsField;

    private string labelField;

    private string descriptionField;

    private string categoryField;

    private object itemField;

    private property[] propertiesField;

    private string representationpropertyField;

    private object item1Field;

    private string idField;

    private bool listedField;

    private string extensibleField;

    public thingType()
    {
        this.listedField = true;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("supported-bridge-type-refs", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("bridge-type-ref", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public bridgeTypeRef[] supportedbridgetyperefs
    {
        get
        {
            return this.supportedbridgetyperefsField;
        }
        set
        {
            this.supportedbridgetyperefsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel-groups", typeof(channelGroups), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("channels", typeof(channels), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public property[] properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("representation-property", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string representationproperty
    {
        get
        {
            return this.representationpropertyField;
        }
        set
        {
            this.representationpropertyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("config-description", typeof(configDescription), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("config-description-ref", typeof(configDescriptionRef), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item1
    {
        get
        {
            return this.item1Field;
        }
        set
        {
            this.item1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool listed
    {
        get
        {
            return this.listedField;
        }
        set
        {
            this.listedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extensible
    {
        get
        {
            return this.extensibleField;
        }
        set
        {
            this.extensibleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class bridgeTypeRef
{

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channelGroupType
{

    private string labelField;

    private string descriptionField;

    private string categoryField;

    private channel[] channelsField;

    private string idField;

    private bool advancedField;

    public channelGroupType()
    {
        this.advancedField = false;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public channel[] channels
    {
        get
        {
            return this.channelsField;
        }
        set
        {
            this.channelsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool advanced
    {
        get
        {
            return this.advancedField;
        }
        set
        {
            this.advancedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channel
{

    private string labelField;

    private string descriptionField;

    private property[] propertiesField;

    private autoupdatepolicy autoUpdatePolicyField;

    private bool autoUpdatePolicyFieldSpecified;

    private string idField;

    private string typeIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public property[] properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public autoupdatepolicy autoUpdatePolicy
    {
        get
        {
            return this.autoUpdatePolicyField;
        }
        set
        {
            this.autoUpdatePolicyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool autoUpdatePolicySpecified
    {
        get
        {
            return this.autoUpdatePolicyFieldSpecified;
        }
        set
        {
            this.autoUpdatePolicyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typeId
    {
        get
        {
            return this.typeIdField;
        }
        set
        {
            this.typeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class property
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "auto-update-policy", Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public enum autoupdatepolicy
{

    /// <remarks/>
    veto,

    /// <remarks/>
    @default,

    /// <remarks/>
    recommend,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class @event
{

    private option[] optionsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public option[] options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class option
{

    private string valueField;

    private string valueField1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField1;
        }
        set
        {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class state
{

    private option[] optionsField;

    private decimal minField;

    private bool minFieldSpecified;

    private decimal maxField;

    private bool maxFieldSpecified;

    private decimal stepField;

    private bool stepFieldSpecified;

    private string patternField;

    private bool readOnlyField;

    public state()
    {
        this.readOnlyField = false;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public option[] options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minSpecified
    {
        get
        {
            return this.minFieldSpecified;
        }
        set
        {
            this.minFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxSpecified
    {
        get
        {
            return this.maxFieldSpecified;
        }
        set
        {
            this.maxFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal step
    {
        get
        {
            return this.stepField;
        }
        set
        {
            this.stepField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stepSpecified
    {
        get
        {
            return this.stepFieldSpecified;
        }
        set
        {
            this.stepFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pattern
    {
        get
        {
            return this.patternField;
        }
        set
        {
            this.patternField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool readOnly
    {
        get
        {
            return this.readOnlyField;
        }
        set
        {
            this.readOnlyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channelType
{

    private string itemtypeField;

    private string kindField;

    private string labelField;

    private string descriptionField;

    private string categoryField;

    private string[] tagsField;

    private state stateField;

    private @event eventField;

    private autoupdatepolicy autoUpdatePolicyField;

    private bool autoUpdatePolicyFieldSpecified;

    private object itemField;

    private string idField;

    private bool advancedField;

    private bool systemField;

    public channelType()
    {
        this.advancedField = false;
        this.systemField = false;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-type", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemtype
    {
        get
        {
            return this.itemtypeField;
        }
        set
        {
            this.itemtypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string kind
    {
        get
        {
            return this.kindField;
        }
        set
        {
            this.kindField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public string[] tags
    {
        get
        {
            return this.tagsField;
        }
        set
        {
            this.tagsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public state state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public @event @event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public autoupdatepolicy autoUpdatePolicy
    {
        get
        {
            return this.autoUpdatePolicyField;
        }
        set
        {
            this.autoUpdatePolicyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool autoUpdatePolicySpecified
    {
        get
        {
            return this.autoUpdatePolicyFieldSpecified;
        }
        set
        {
            this.autoUpdatePolicyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("config-description", typeof(configDescription), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("config-description-ref", typeof(configDescriptionRef), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool advanced
    {
        get
        {
            return this.advancedField;
        }
        set
        {
            this.advancedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool system
    {
        get
        {
            return this.systemField;
        }
        set
        {
            this.systemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
[System.Xml.Serialization.XmlRootAttribute("config-description", Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0", IsNullable = false)]
public partial class configDescription
{

    private parameterGroup[] parametergroupField;

    private parameter[] parameterField;

    private string uriField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter-group", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public parameterGroup[] parametergroup
    {
        get
        {
            return this.parametergroupField;
        }
        set
        {
            this.parametergroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public parameter[] parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public partial class parameterGroup
{

    private string labelField;

    private string descriptionField;

    private string contextField;

    private bool advancedField;

    private bool advancedFieldSpecified;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string context
    {
        get
        {
            return this.contextField;
        }
        set
        {
            this.contextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool advanced
    {
        get
        {
            return this.advancedField;
        }
        set
        {
            this.advancedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool advancedSpecified
    {
        get
        {
            return this.advancedFieldSpecified;
        }
        set
        {
            this.advancedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public partial class parameter
{

    private string contextField;

    private bool requiredField;

    private string defaultField;

    private string labelField;

    private string descriptionField;

    private optionsTypeOption[] optionsField;

    private bool limitToOptionsField;

    private bool limitToOptionsFieldSpecified;

    private filterTypeCriteria[] filterField;

    private bool advancedField;

    private bool advancedFieldSpecified;

    private bool verifyField;

    private bool verifyFieldSpecified;

    private string multipleLimitField;

    private string unitLabelField;

    private string nameField;

    private parameterType typeField;

    private string groupNameField;

    private decimal minField;

    private bool minFieldSpecified;

    private decimal maxField;

    private bool maxFieldSpecified;

    private decimal stepField;

    private bool stepFieldSpecified;

    private string patternField;

    private bool required1Field;

    private bool required1FieldSpecified;

    private bool readOnlyField;

    private bool readOnlyFieldSpecified;

    private bool multipleField;

    private bool multipleFieldSpecified;

    private unitType unitField;

    private bool unitFieldSpecified;

    public parameter()
    {
        this.requiredField = false;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string context
    {
        get
        {
            return this.contextField;
        }
        set
        {
            this.contextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required
    {
        get
        {
            return this.requiredField;
        }
        set
        {
            this.requiredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @default
    {
        get
        {
            return this.defaultField;
        }
        set
        {
            this.defaultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("option", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public optionsTypeOption[] options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool limitToOptions
    {
        get
        {
            return this.limitToOptionsField;
        }
        set
        {
            this.limitToOptionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool limitToOptionsSpecified
    {
        get
        {
            return this.limitToOptionsFieldSpecified;
        }
        set
        {
            this.limitToOptionsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("criteria", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public filterTypeCriteria[] filter
    {
        get
        {
            return this.filterField;
        }
        set
        {
            this.filterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool advanced
    {
        get
        {
            return this.advancedField;
        }
        set
        {
            this.advancedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool advancedSpecified
    {
        get
        {
            return this.advancedFieldSpecified;
        }
        set
        {
            this.advancedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool verify
    {
        get
        {
            return this.verifyField;
        }
        set
        {
            this.verifyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool verifySpecified
    {
        get
        {
            return this.verifyFieldSpecified;
        }
        set
        {
            this.verifyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string multipleLimit
    {
        get
        {
            return this.multipleLimitField;
        }
        set
        {
            this.multipleLimitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unitLabel
    {
        get
        {
            return this.unitLabelField;
        }
        set
        {
            this.unitLabelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public parameterType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groupName
    {
        get
        {
            return this.groupNameField;
        }
        set
        {
            this.groupNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minSpecified
    {
        get
        {
            return this.minFieldSpecified;
        }
        set
        {
            this.minFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxSpecified
    {
        get
        {
            return this.maxFieldSpecified;
        }
        set
        {
            this.maxFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal step
    {
        get
        {
            return this.stepField;
        }
        set
        {
            this.stepField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stepSpecified
    {
        get
        {
            return this.stepFieldSpecified;
        }
        set
        {
            this.stepFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pattern
    {
        get
        {
            return this.patternField;
        }
        set
        {
            this.patternField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("required")]
    public bool required1
    {
        get
        {
            return this.required1Field;
        }
        set
        {
            this.required1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool required1Specified
    {
        get
        {
            return this.required1FieldSpecified;
        }
        set
        {
            this.required1FieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool readOnly
    {
        get
        {
            return this.readOnlyField;
        }
        set
        {
            this.readOnlyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool readOnlySpecified
    {
        get
        {
            return this.readOnlyFieldSpecified;
        }
        set
        {
            this.readOnlyFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool multiple
    {
        get
        {
            return this.multipleField;
        }
        set
        {
            this.multipleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool multipleSpecified
    {
        get
        {
            return this.multipleFieldSpecified;
        }
        set
        {
            this.multipleFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public unitType unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitSpecified
    {
        get
        {
            return this.unitFieldSpecified;
        }
        set
        {
            this.unitFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public partial class optionsTypeOption
{

    private string valueField;

    private string valueField1;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField1;
        }
        set
        {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public partial class filterTypeCriteria
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public enum parameterType
{

    /// <remarks/>
    text,

    /// <remarks/>
    integer,

    /// <remarks/>
    @decimal,

    /// <remarks/>
    boolean,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public enum unitType
{

    /// <remarks/>
    A,

    /// <remarks/>
    cd,

    /// <remarks/>
    K,

    /// <remarks/>
    kg,

    /// <remarks/>
    m,

    /// <remarks/>
    mol,

    /// <remarks/>
    s,

    /// <remarks/>
    Bq,

    /// <remarks/>
    C,

    /// <remarks/>
    F,

    /// <remarks/>
    Gy,

    /// <remarks/>
    H,

    /// <remarks/>
    Hz,

    /// <remarks/>
    J,

    /// <remarks/>
    kat,

    /// <remarks/>
    lm,

    /// <remarks/>
    lx,

    /// <remarks/>
    N,

    /// <remarks/>
    Pa,

    /// <remarks/>
    rad,

    /// <remarks/>
    S,

    /// <remarks/>
    sr,

    /// <remarks/>
    Sv,

    /// <remarks/>
    T,

    /// <remarks/>
    V,

    /// <remarks/>
    W,

    /// <remarks/>
    Wb,

    /// <remarks/>
    Cel,

    /// <remarks/>
    O,

    /// <remarks/>
    g,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("m/s2")]
    ms2,

    /// <remarks/>
    m2v,

    /// <remarks/>
    m3,

    /// <remarks/>
    kph,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("%")]
    Item,

    /// <remarks/>
    l,

    /// <remarks/>
    ms,

    /// <remarks/>
    min,

    /// <remarks/>
    h,

    /// <remarks/>
    d,

    /// <remarks/>
    week,

    /// <remarks/>
    y,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
public partial class configDescriptionRef
{

    private string uriField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channelGroups
{

    private channelGroup[] channelgroupField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel-group", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public channelGroup[] channelgroup
    {
        get
        {
            return this.channelgroupField;
        }
        set
        {
            this.channelgroupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channelGroup
{

    private string labelField;

    private string descriptionField;

    private string idField;

    private string typeIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string label
    {
        get
        {
            return this.labelField;
        }
        set
        {
            this.labelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typeId
    {
        get
        {
            return this.typeIdField;
        }
        set
        {
            this.typeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://eclipse.org/smarthome/schemas/thing-description/v1.0.0")]
public partial class channels
{

    private channel[] channelField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public channel[] channel
    {
        get
        {
            return this.channelField;
        }
        set
        {
            this.channelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0")]
[System.Xml.Serialization.XmlRootAttribute("config-descriptions", Namespace = "http://eclipse.org/smarthome/schemas/config-description/v1.0.0", IsNullable = false)]
public partial class configdescriptions
{

    private configDescription[] configdescriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("config-description", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public configDescription[] configdescription
    {
        get
        {
            return this.configdescriptionField;
        }
        set
        {
            this.configdescriptionField = value;
        }
    }
}
